name: deploy KinD in github action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy KinD
    steps:
    - name: Get current date and time before deploy
      id: current_time_bd
      run: |
        echo "Current date and time before deploy is: $(date +'%T-%Y-%m-%d')" >> report.log 2>&1
      
    - name: Setup KinD
      uses: helm/kind-action@v1.4.0
      
    - name: Get current date and time after deploy
      id: current_time_ad
      run: |
        echo "Current date and time after deploy is: $(date +'%T-%Y-%m-%d')" >> report.log 2>&1
        
    - name: Get info from KinD
      run: |
        echo "nodes: $(kubectl get nodes | grep -c 'Ready')\n" >> report.log 2>&1
        echo "$(kubectl get nodes)\n" >> report.log 2>&1
        echo "Version of k8s: $(kubectl version)\n" >> report.log 2>&1      
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        path: report.log